### ISSUE TITLE
[BUG] This error is raised when using Implicit differentiation module.

### ISSUE THREAD

**Issue by floatingCatty** [metaopt/torchopt#123]
## Describe the bug

The forward is normal, but when I compute gradient, it raised this bug. Seems it does not recognize the parameter that I requires grad, or am I using this function in a wrong way? Please help me in this, Thanks.

## To Reproduce
```python 
def sgf_stationary(params, meta_params, data):
    gs, ee, s00, h00, s01, h01 = params
    left = meta_params[0]
    if not left:
        gs_ = ee*s00 - h00 - (ee * s01 - h01) @ gs @ (ee * s01.conj().T - h01.conj().T)
        gs_ = tLA.pinv(gs_)
    else:
        gs_ = ee*s00 - h00 - (ee * s01.conj().T - h01.conj().T) @ gs @ (ee * s01 - h01)
        gs_ = tLA.pinv(gs_)
return gs_ - gs
@torchopt.implicit_diff.custom_root(sgf_stationary, argnums=[1,2,3,4,5], solve=torchopt.linear_solve.solve_normal_cg(maxiter=5, atol=0),)
def sgf(params, meta_params, data):
    _, ee, S, H, s01, h01 = params
    left, method = meta_params
    if method == 'GEP':
        gs = calcg0(ee, H, S, h01, s01, left=left)
    else:
        h10 = h01.conj().T
        s10 = s01.conj().T
        alpha, beta = h10 - ee * s10, h01 - ee * s01
        eps, epss = H.clone(), H.clone()
        converged = False
        iteration = 0
        while not converged:
            iteration += 1
            oldeps, oldepss = eps.clone(), epss.clone()
            oldalpha, oldbeta = alpha.clone(), beta.clone()
            tmpa = tLA.solve(ee * S - oldeps, oldalpha)
            tmpb = tLA.solve(ee * S - oldeps, oldbeta)

            alpha, beta = torch.mm(oldalpha, tmpa), torch.mm(oldbeta, tmpb)
            eps = oldeps + torch.mm(oldalpha, tmpb) + torch.mm(oldbeta, tmpa)
            if left:
                epss = oldepss + torch.mm(oldalpha, tmpb)
            else:
                epss = oldepss + torch.mm(oldbeta, tmpa)
            LopezConvTest = torch.max(alpha.abs() + beta.abs())

            if LopezConvTest < 1.0e-40:
                gs = (ee * S - epss).inverse()

                if left:
                    test = ee * S - H - torch.mm(ee * s10 - h10, gs.mm(ee * s01 - h01))
                else:
                    test = ee * S - H - torch.mm(ee * s01 - h01, gs.mm(ee * s10 - h10))
                myConvTest = torch.max((test.mm(gs) - torch.eye(H.shape[0], dtype=h01.dtype)).abs())
                if myConvTest < 1.0e-5:
                    converged = True
                    if myConvTest > 1.0e-8:
                        v = "RIGHT"
                        if left: v = "LEFT"
                        print(
                            "WARNING: Lopez-scheme not-so-well converged for " + v + " electrode at E = %.4f eV:" % ee.real.item(),
                            myConvTest.item())
                else:
                    print("Lopez-Sancho", myConvTest,
                            "Error: gs iteration {0}".format(iteration))
                    raise ArithmeticError("Criteria not met. Please check output...")
    return gs
```

The code is in above.

```python
Traceback (most recent call last):
  File "/data/ADNEGF/calc/surface_green.py", line 370, in <module>
    torch.autograd.grad(gs.sum(), params)
  File "/root/miniconda3/envs/torch/lib/python3.9/site-packages/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

## Expected behavior

The backward pass can behave as usual.

```python
import sys, torch, functorch, torchopt
import torch
import torch.linalg as tLA
import scipy.linalg as SLA
import torchopt
```

## Reason and Possible fixes

If you know or suspect the reason for this bug, paste the code lines and suggest modifications.

## Checklist

- [ ] I have checked that there is no similar issue in the repo. (**required**)
- [ ] I have read the [documentation](https://torchopt.readthedocs.io). (**required**)
- [ ] I have provided a minimal working example to reproduce the bug. (**required**)

**Comment by Benjamin-eecs** [comment]
Hi @floatingCatty , I was wondering which version of torchopt, functorch, system you used that produced such bug report?

You can try the following code snippet to get that

```python
import sys, torch, functorch, torchopt
print(sys.version, sys.platform)
print(torchopt.__version__, torch.__version__, functorch.__version__)
```
